name: "Send Mail"
on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: "Install Dependencies"
        run: python -m pip install --upgrade pip  # If required dependencies exist
      
      - name: "Send Mail"
        run: python script.py
        env:
          WORKFLOW_NAME: ${{ github.workflow }}
          REPO_NAME: ${{ github.repository }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}