name: "TEST"
on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      
      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 

      - name: "Install Dependencies"
        run: python -m pip install --upgrade pip 
         
      - name: "Verify Files"
        run: ls -R  

      - name: "Send Mail"
        run: python print.py

      - name: "Trigger Another Pipeline on Failure"
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        run: gh workflow run alert.yml --repo ${{ github.repository }} --ref ${{ github.ref }}
